baseURL = "/"
theme = "hugo-whisper-theme"
languageCode = "en-us"
title = "Privacy-Enhancing Technologies (PETS)"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "About"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Content"
    url = "/course/"
    weight = 2

[params]
  matomo_analytics_id="11"
  matomo_analytics_host="//matomo.nysos.net/"
  homepage_button_link = '/course'
  homepage_button_text = 'Content'
  homepage_intro = 'Privacy-Enhancing Techologies Lecture Archive'
  homepage_image = ''

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "Lecture Content Archive for Privacy-Enhancing Technologies (PETS)."
    meta_og_title = "Privacy-Enhancing Technologies (PETS)"
    meta_og_type = "website"
    meta_og_image = "https://avatars.githubusercontent.com/u/182622536?"
    meta_og_description = "Lecture notes and challenges for our Privacy-Enhancing Technologies (PETS) university course."
    meta_twitter_card = "summary"

  [params.logo]
      mobile = "/images/logo-mobile.svg"
      standard  = "/images/logo.svg"

  [params.footer]
    copyright_text = 'Except where otherwise noted, content on this site is licensed under a <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0 license</a>.'
